### PR TITLE
Fixed StateMachine bug where timed states that have previously been r…

### PR DESCRIPTION
**Pull request by amorygalili**
…un will expire immediately if run a second time

### CODE REVIEW

**Comment by amorygalili** [comment]
Fixes this issue: #89

**Comment by amorygalili** [comment]
Fixes this issue: #88

**Comment by auscompgeek** [comment]
Heh, this would explain the issue we had with timed states the past few years.

**Comment by virtuald** [comment]
Thanks for fixing this! Pushed a new release.

**Pull request merged**
