### PR TITLE
Throw an error in sim/test if autonomous package has no init file

### PR DESCRIPTION
**Pull request by ArchdukeTim**

### CODE REVIEW

**Comment by auscompgeek** [comment]
See #74.

**Comment by auscompgeek** [comment]
Since this has merge conflicts, and this is definitely not the approach we'd want to take, I'm closing this. If anyone would like to fix the behaviour here such that an "implicit" package works as expected, a PR for that would be most welcome.

**Comment by virtuald** [comment]
tbh this wasn't that bad. Not sure why I didn't merge it.

**Comment by ArchdukeTim** [comment]
What situation would case autonomous_pkg to have `__file__` but it also be `None`?

**Comment by virtuald** [comment]
See the title of the PR? :grimacing:

**Comment by ArchdukeTim** [comment]
I guess my question is, how would you make a package that _doesn't_ have the '__file__' attribute

**Comment by virtuald** [comment]
Exactly what the title of the PR says. 

If there's no `__init__.py` then the package has no `__file__` attribute.

**Comment by ArchdukeTim** [comment]
Does that mean `hasattr(autonomous_pkg, "__file__")` is always true?

**Pull request closed without merging**
