### PR TITLE
Refactor out magicbot dependency injection

### PR DESCRIPTION
**Pull request by auscompgeek**
This should be better testable, and will make it easier to implement
different flavours on the injection requests.

(will eventually write/untangle tests for this before merging)

### CODE REVIEW

**Comment by auscompgeek** [comment]
Well, I managed to make the existing tests work at least.

**Comment by virtuald** [comment]
Due to the scope of changes, my inclination is to not merge this until the end of season unless there's a significantly compelling reason?

**Comment by virtuald** [comment]
It does look pretty nice though.

**Comment by auscompgeek** [comment]
This is mostly to prepare for performing DI on the constructor. Happy to leave this for next season.

I've discovered that a nice side effect of this is that if an error is raised the locals give you a bit more information though.

**Comment by auscompgeek** [comment]
I'll probably try to untangle getting these tests working from this PR. Seems worthwhile anyway.

**Review by virtuald — APPROVED** [review]

**Pull request merged**
