### PR TITLE
Default to class name for auto modes

### PR DESCRIPTION
**Pull request by twinters007**
Makes subclassing automodes a little easier. Just a thought

### CODE REVIEW

**Comment by auscompgeek** [comment]
Uh, what? Only classes with a `MODE_NAME` are picked up as autonomous modes, so this is a no-op.

**Comment by virtuald** [comment]
Yeah. Otherwise how do we choose which objects are autonomous modes?

I suppose you could inherit from something, or add a `MAGIC_AUTONOMOUS = True` attribute...

**Comment by virtuald** [comment]
Another alternative is just any class that ends in the word 'Autonomous'...

**Comment by twinters007** [comment]
Oh I assumed it had to do with the autonomous folder.

**Pull request closed without merging**
