### PR TITLE
Added Command based docs

### PR DESCRIPTION
**Pull request by FRC2539**
This adds a first version of our ideas for how to use the Command based paradigm in Python. We aren't sure if there is anything else we need to do to make it work properly with the documentation site. It appears that a lot of things are automatic. If there is something else we need to add, let us know.

We also updated our module's base class to call the HAL methods whenever a mode starts instead of on each iteration.

### CODE REVIEW

**Comment by virtuald** [comment]
This is a great start! A lot of things are seemingly automatic, but in order for it to show up in the sidebar, you have to add it to the index page (index.rst).

For future reference, if you have `sphinx` and `sphinx-rtd-theme` installed, you can build the documentation yourself locally using "make html" or on Windows "make.bat html".

**Comment by FRC2539** [comment]
What do we need to edit in [index.rst](https://github.com/robotpy/robotpy-wpilib-utilities/blob/master/docs/index.rst) to make our page show up?

**Comment by virtuald** [comment]
I updated the docs in f83dd3a, and added the wpilib command module docs as well. I don't think they'll all show up on rtd yet, because an updated wpilib released hasn't been pushed to pypi. However, I expect to migrate all of this to a unified documentation repository, at which point this will be moot.

**Comment by FRC2539** [comment]
Thanks.

**Pull request merged**
