### PR TITLE
Create customizable iter functions

### PR DESCRIPTION
**Pull request by ArchdukeTim**

### CODE REVIEW

**Comment by ArchdukeTim** [comment]
This should allow teams to add `teleopPeriodic` to their autonomous calls when the time is right by doing `self.auto_iter_fns = [self.teleopPeriodic, self._execute_components]`, among other customizable things

**Comment by virtuald** [comment]
This doesn't feel right.

**Comment by virtuald** [comment]
I think I'd rather have it as an option in the base class, which if set to True would add teleopPeriodic to that tuple, instead of exposing it directly.

**Comment by ArchdukeTim** [comment]
Yeah I didn't like having to manually add the execute components stuff, but I think we should allow adding additional methods. But they have to be added before execute_components or else they'll be overrided. Perhaps making this a property with a setter that prepends the list?

**Comment by virtuald** [comment]
Why should we allow adding additional methods?

**Comment by ArchdukeTim** [comment]
What if there's a method you want called every loop during autonomous? I guess you could just add 
```
if self.isAutonomous() and self.isEnabled():
  ...
``` 
in robotPeriodic though. Perhaps it's not really necesary

**Pull request closed without merging**
