### PR TITLE
looptimer: Update for WPILib 2023

### PR DESCRIPTION
**Pull request by auscompgeek**
Spotted this whilst checking what needed type hints for type checking in `robotpy_ext`.

- Fix hasPeriodPassed AttributeError
- Update IterativeRobot reference to TimedRobot

### CODE REVIEW

**Comment by auscompgeek** [comment]
Uh oh. Why are entirely unrelated magicbot StateMachine tests failing?

**Comment by virtuald** [comment]
Have we updated Magicbot for 2023? I don't recall.

**Comment by auscompgeek** [comment]
It worked in #195 so…

**Comment by auscompgeek** [comment]
Gonna merge this for now and look into the magicbot test failures later, since mypy is saying this is obviously broken. Fixing these type check errors will be a prerequisite to adding a `py.typed`.

**Pull request merged**
